test:
  image: php:latest
  
  # cache between builds
  cache:
    paths:
      - vendor/
  
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq git libcurl4-gnutls-dev
    # Install PHP extensions
    - docker-php-ext-install curl
    # Install & enable Xdebug for code coverage reports
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    # Install and run Composer
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install

  script:
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text